---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Refreshing Repositories
      package:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/dotfiles.yml
    - include: tasks/cron.yml


# vim: set sw=2 expandtab:
