---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - base-devel
        - syncthing
        - tmux

# vim: set sw=2 expandtab:
