- name: Installing ansible-pull Cronjob
  cron:
    user: root
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/jameh/ansible.git"
  become: yes
