- name: Creating Dotfile Directories
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
    - config
    - config/bspwm

- name: Linking Dotfiles
  file:
    src: '{{ ansible_env.PWD }}/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
    - config/bspwm/bspwmrc
    - gitconfig
    - tmux.conf
    - zshrc

- name: Copying /etc Config Files
  copy:
    src: '{{ ansible_env.PWD }}/files/etc/{{ item }}'
    dest: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - X11/Xkbmap
    - interception/udevmon.d/caps2esc.yaml
  become: yes

# vim: set sw=2 expandtab:
