- name: Creating dotfile directories
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
    - config

- name: Linking dotfiles
  file:
    src: '{{ ansible_env.PWD }}/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
    - gitconfig
    - tmux.conf
    - zshrc

# vim: set sw=2 expandtab:
