- name: Creating Dotfile Directories
  file:
    path: '~/.{{ item }}'
    state: directory
  loop:
    - config
    - config/bspwm
    - config/sxhkd
    - config/systemd
    - config/alacritty
    - tmux
  tags:
    - dots

- name: Linking Dotfiles
  file:
    src: '{{ ansible_env.PWD }}/files/dotfiles/{{ item }}'
    path: '~/.{{ item }}'
    state: link
  loop:
    - config/bspwm/bspwmrc
    - config/sxhkd/sxhkdrc
    - config/systemd/user
    - config/alacritty/alacritty.yml
    - local/lib
    - gitconfig
    - tmux.conf
    - zshrc
  tags:
    - dots

- name: Copying /etc Config Files
  copy:
    src: '{{ ansible_env.PWD }}/files/etc/{{ item }}'
    dest: '/etc/{{ item }}'
    owner: root
    group: root
    mode: '0644'
  loop:
    - X11/xorg.conf.d/20-keyboard.conf
    - interception/udevmon.d/caps2esc.yaml
  become: yes

# vim: set sw=2 expandtab:
