- name: Installing Packages
  package:
    name:
      - alsa-utils
      - base-devel
      - bspwm
      - sxhkd
      - lightdm
      - lightdm-gtk-greeter
      - xorg-server
      - syncthing
      - tmux
      - cronie
      - pkgfile
      - man-db
      - alacritty
      - chromium
      - arch-wiki-lite
      - rofi
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-cjk
  become: yes
  tags:
    - install

- name: Creating ~/.local/src
  file:
    path: "{{ lookup('env', 'HOME') }}/.local/src"
    state: directory

- name: Cloning yay
  git:
    repo: 'https://aur.archlinux.org/yay.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/src/yay"

- name: Building and Installing yay
  command: chdir="{{ lookup('env', 'HOME') }}/.local/src/yay" makepkg -si --noconfirm

- name: Installing AUR Packages
  command: yay -S {{ item }} --noconfirm
  loop:
    - interception-caps2esc
    - nerd-fonts-droid-sans-mono

# vim: set sw=2 expandtab:
